### ISSUE TITLE
how to handle potential pre-releases? should we make those stable? make an opt-in cfg option? needs discussion.

### ISSUE THREAD

**Issue by steviegt6** [steviegt6/holocure-launcher#18]
https://github.com/steviegt6/holocure-launcher/blob/e2f2dea8584dfb8f70c536be03a87ec042e60b60/src/HoloCure.Launcher.Desktop/Updater/SquirrelUpdateManager.cs#L64-L69

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in e2f2dea8584dfb8f70c536be03a87ec042e60b60.

**Comment by MemeHoovy** [comment]
quit spamming issues

**Comment by steviegt6** [comment]
Overhauled updating system has support for release channels.
